### ISSUE TITLE
Crystal growth chamber causes crash

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#2] opened 2015-01-15 01:58 UTC
I believe you guys are aware of the issue but placing the AE2Stuff crystal growth chamber causes the server to crash

**Comment by downslope7** [comment] 2015-01-15 02:17
This is caused by AE2Stuff being built against an old version of AE2. There's [a new release out](http://minecraft.curseforge.com/mc-mods/225194-ae2-stuff/files), targeting for v1.0.1.

**Comment by downslope7** [comment] 2015-01-18 00:22
Should be fixed in v1.1.0.

**Closed by downslope7** 2015-01-18 00:22 UTC
Labels: bug
